### ISSUE TITLE
Workflow does not auto-update

### ISSUE THREAD

**Issue by altern8tif** [vdesabou/alfred-spotify-mini-player#187]
The workflow doesn't seem to autoupdate to the newest version (7.1).  I get the following screenshot instead (defaults to my Alfred fallback results).  Is this a bug?

P.S. I've changed the value of my `c_spot_mini` variable to `spot`.

![screen shot 2017-04-11 at 8 50 25 am](https://cloud.githubusercontent.com/assets/5793364/24888183/fb7f9d38-1e93-11e7-8a10-08dc2f8c4e31.png)

**Comment by vdesabou** [comment]
Can you try again, I've fixed the issue.

Thanks

**Comment by altern8tif** [comment]
Would I need to re-download the workflow?

I'm currently on 7.0.1 and it still doesn't seem to auto-update to 7.1.  Getting the same result as above.

**Comment by vdesabou** [comment]
Can you activate debug traces for the workflow in Alfred and show me output ?

**Comment by vdesabou** [comment]
It's working for me now:

![screenshot 2017-04-11 at 12 04 08](https://cloud.githubusercontent.com/assets/4061923/24903897/186de628-1eaf-11e7-966a-62f7ba44f00e.jpg)

**Comment by altern8tif** [comment]
[Gist](https://gist.github.com/altern8tif/7159be81dc9d91f8b9c0b265f4e028bd) of log from Alfred. 
 Also appended the [link](https://transfer.sh/sUSqO/spot_mini_debug_1183466762.zip) to the debug files.  Is that what you needed?

The keyword trigger seems to disappear on your workflow, but not mine... ie it says "spot Check for update...>" when I tab into the individual options.

**Comment by vdesabou** [comment]
Thanks.
That's a bug I've fixed in 7.1..
You can download latest version from here http://alfred-spotify-mini-player.com and install it by double-clicking on it

**Comment by altern8tif** [comment]
Sweet.  It's all good now.  Thanks for the quick turnaround 👍
